config/routes.rb
Rails.application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config

get 'profile/:id'=> 'pages#profile' ,as: 'profile'
get 'followers/:id'=> 'pages#followers' ,as: 'followers'
get 'following/:id'=> 'pages#following' ,as: 'following'
resources :pages, only: [:index]

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
    get 'like', to: "posts#like"
    get 'unlike', to: "posts#unlike"
  end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
resources :relationships,       only: [:create, :destroy]

    ActiveAdmin.routes(self)

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, presence: true, length:{minimum:1};
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :comment_owner, only: [:edit, :update, :destroy]
     def comment_owner
       @post=Post.find(params[:post_id])
       @comment=@post.comments.find(params[:id])
      unless @comment.user_id == current_user.id||@comment.post.user_id==current_user.id
       flash[:notice] = 'Access denied as you are not owner of this Job'
       redirect_to post_path(@post)
      end
     end
  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    flash[:success]='Comment deleted successfuly'
    redirect_to post_path(@post)
  end

  def create
      @post= Post.find( params[:post_id] )
      @comment= @post.comments.create(params[:comment].permit(:body,:user_id))
      flash[:success]='Comment created successfuly'
      redirect_to post_path(@post)
  end

  def edit
    @post= Post.find( params[:post_id] )
    @comment=@post.comments.find(params[:id])
  end

  def update
    @post= Post.find( params[:post_id] )
    @comment=@post.comments.find(params[:id])
    if @comment.update(params[:comment].permit(:body,:user_id))
        flash[:success]='Comment updated successfuly'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end
  # private
  #
  #   def permit_comment
  #     params.require(:comment).permit(:name,:body)
  #   end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix ">
  <div class="comment_content ">
    <div class="row">

        <div class="col s2 m1 l1" style="margin-left:5px"> <%= image_tag comment.user.avatar.url(:thumb),class:"circle responsive-img"%></div>
        <div class="col s3 m3 l3" style="margin:10px 0 0 5px;"><strong > <%= link_to comment.user.username, profile_path(comment.user), style:"color:green;"%></strong></div>
        <div class="col right">
                <% if(user_signed_in? && (current_user.id == comment.user_id || current_user.id == comment.post.user_id))%>

                    <a class=" dropdown-button red-text" data-constrainWidth="false" data-beloworigin="true" data-activates='comment_options<%=comment.id%>'><i class="fa fa-chevron-circle-down" aria-hidden="true"></i></a>
                     <ul id='comment_options<%=comment.id%>' class='dropdown-content'>

                          <li><%= link_to [comment.post,comment], method: :delete, data: {confirm:"Are you sure, do you want to 'DELETE' this comment?"} do %>
                              <i class="material-icons red-text"title="delete comment" style="margin-right:2px">delete</i> delete
                            <% end %>
                          </li>

                        <% if (current_user.id == comment.user_id)%>
                            <li> <%= link_to  edit_post_comment_path(comment.post,comment) do%>
                              <i class="material-icons green-text" title="edit comment" style="margin-right:2px"> edit</i> edit
                              <%end%>
                            </li>
                        <% end %>

                      </ul>
               <% end %>
        </div>

   </div>

<div class="row">
  <p class="comment_body grey-text" style="margin-left:15%;margin-right:15%;margin-top:0"><%=comment.body%></p>
  <p class="comment_time"  style="margin-left:5%"><%=time_ago_in_words(comment.created_at)%> Ago</p>
</div>

  </div>

</div>
<hr>

app/views/comments/_form.html.erb
<%= form_for ([@post,@post.comments.build]) do |f| %>


  <%=  f.hidden_field :user_id , :value => current_user.id%>

  <div class="row">
      <div class="col s2 m1 l1" style="margin-left:5px"> <%= image_tag current_user.avatar.url(:thumb),class:"circle responsive-img"%></div>
      <div class="col s3 m2 l2" style="margin:10px 0 0 5px;"><strong > <%= link_to current_user.username, profile_path(current_user), style:"color:green;"%></strong></div>
      <div class="col s7 m8 l8">
        <%= f.text_area :body,placeholder:"enter your comment here"%>
      </div>
  </div>

  <%= f.submit 'Comment', class: 'btn right' %>
  <br><br>

<%end%>

app/views/comments/edit.html.erb
<%= form_for ([@post,@comment]) do |f| %>


  <%=  f.hidden_field :user_id , :value => current_user.id%>
  <p class="comment_name green-text"><strong><%=current_user.username%></strong></p>
  <%= f.text_area :body %>
  <%= f.submit 'Comment', class: 'btn' %>

<%end%>