config/routes.rb
Rails.application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config

get 'profile/:id'=> 'pages#profile' ,as: 'profile'
get 'followers/:id'=> 'pages#followers' ,as: 'followers'
get 'following/:id'=> 'pages#following' ,as: 'following'
resources :pages, only: [:index]

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
    get 'like', to: "posts#like"
    get 'unlike', to: "posts#unlike"
  end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
resources :relationships,       only: [:create, :destroy]

    ActiveAdmin.routes(self)

end

app/views/pages/_followunfollow_button.html.erb
<% if current_user.id == user.id %>
  <%= link_to 'Edit Profile',edit_user_registration_path,class:"text-lighten-1 btn" %>
<%else%>
    <div id="ff_button<%=user.id%>">
        <% if current_user.following?(user) %>
              <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                       html: { method: :delete }, remote: true) do |f| %>
                 <%= f.submit "Unfollow", class: "btn" %>
              <% end %>
        <% else %>
              <%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
                <div><%= hidden_field_tag :followed_id, user.id %></div>
                <%= f.submit "Follow", class: "btn btn-primary" %>
              <% end %>
        <% end %>
    </div>
<% end %>

app/views/pages/_show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col m5">
    <section class="user_info">

        <span><%= link_to profile_path(@user)  do%>
              <h4><%= @user.username %></h4>
              <%end%>
        </span>

        <div class="followers_following_count">
            <a href="<%= followers_path(@user) %>"> <strong id="followers<%=@user.id%>" class="stat"> <%= @user.followers.count %></strong> followers</a>
            <a href="<%= following_path(@user) %>"> <strong id="following<%=@user.id%>" class="stat"> <%= @user.following.count %></strong> following</a>
        </div>

    <%= render partial: "followunfollow_button", object:  @user, as: 'user' %>

    </section>
  </aside>
  <div class="col m7">
    <h3><%= @title%></h3>
    <% if @fusers.any? %>
          <div class="users_follow">
             <% @fusers.each do |user|%>

             <div class="row card " style="padding:5px 0 5px 0">

               <div class="col s1 m1 l1" style="margin-left:5px"> <%= image_tag user.avatar.url(:thumb),class:"circle responsive-img"%></div>
               <div class="col s3 m3 l3" style="margin:10px 0 0 5px;"><strong> <%= link_to user.username, profile_path(user) %></strong></div>
               <div class="right col valign-wrapper">
                 <%= render "pages/followunfollow_button",:user => user%>
               </div>

             </div>

             <%end%>
          </div>

    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<h5 class="">showing search results for "<%=params[:search]%>", <%= pluralize(@users.count,"match")%> </h5>
<br>
<% @users.each do |user| %>
    <div class="row card " style="padding:5px 0 5px 0">

      <div class="col s1 m1 l1" style="margin-left:5px"> <%= image_tag user.avatar.url(:thumb),class:"circle responsive-img"%></div>
      <div class="col s3 m3 l3" style="margin:10px 0 0 5px;"><strong> <%= link_to user.username, profile_path(user) %></strong></div>
      <div class="right col">
        <%= render "pages/followunfollow_button",:user => user%>
      </div>

    </div>

<% end %>

app/views/pages/profile.html.erb
<div class="row" style="margin: 5% 5% 5% 5%;">

    <div class="col l3 s3 m3 "><%= image_tag @user.avatar.url(:thumb),class:"circle responsive-img z-depth-3" %></div>

    <div class="col l3 m3 s2 empty"></div>

    <div class="col l5 followers_following_count" style=" margin-top:5%">

        <div class="row center">
            <div class="col l1 m0 s0  empty"></div>
            <div class="col l3 m3 s3" ><a class="grey-text text-darken-2" href="#posts"> <div class="row center" style="font-weight: bold;"><%= @posts.count%></div> <div class="row center">posts </div></a></div>
            <div class="col l4 m5 s5"><a class="grey-text text-darken-2" href="<%= followers_path(@user) %>"> <div id="followers<%=@user.id%>" class="row center" style="font-weight: bold;"> <%= @user.followers.count %></div> <div class="row"> followers </div></a></div>
            <div class="col l4 m4 s4"><a class="grey-text text-darken-2" href="<%= following_path(@user) %>"> <div id="following<%=@user.id%>" class="row center" style="font-weight: bold;"> <%= @user.following.count %></div> <div class="row"> following</div></a></div>
            <div class="col l0 m0 s0 empty"></div>
        </div>
        <div class="row center">
          <%= render partial: "followunfollow_button", object:  @user, as: 'user' %>
       </div>

    </div>

</div>

<div class="row description" style="margin-left:12%;">
    <strong><%=@user.username.capitalize%></strong>  &nbsp <%= @user.about%><br>
    <strong>Birth</strong> &nbsp<%=@user.date_of_birth.to_date%><br>
    <strong>Gender</strong>
    &nbsp
    <%if @user.is_female %>
        Female
    <%else%>
        Male
    <%end%>
</div>

<div id="posts">
      <% @posts.each do |post|%>
      <br>
            <div class=" row single_post hoverable">
              <div class="col s12 card">
                   <div class="card-action header row " style="padding:12px 10px 6px 10px; ">

                       <div class="col s1 l1 m1 left ">
                         <%= link_to profile_path(post.user) do%>
                           <div class="blue-text row valign-wrapper">
                             <div class="col s8 m8 l8"> <%= image_tag post.user.avatar.url(:thumb),class:"circle responsive-img"%></div>
                             <div class="col s1 m1 l1 valign-wrapper" style:" padding-right:20px;"> <%= post.user.username.capitalize %></div>
                           </div>
                         <%end%>
                       </div>

                       <div class="right col"> <%=time_ago_in_words(post.created_at)%> ago</div>

                 </div>

                   <br>
                   <%= link_to post_path(post) do %>
                   <div class="center">
                      <%= image_tag post.image.url(:medium), class:"responsive-img" %>
                    </div>
                    <%end%>
                   <br>

                   <hr style="border: 0; border-top: 1px solid rgba(160, 160, 160, 0.2);">

                   <div class="fame row" style="padding-top:1%;padding-bottom:2%; margin:0;">
                     <div class="col l5 m5 s4"></div>
                       <div class="col l1 m1 s2">
                         <strong><%= post.get_likes.size %></strong> <i class="fa fa-heart" style="color:#ff0000" aria-hidden="true"></i>
                       </div>
                       <div class="col l2 m2 s2">
                       <strong><%=post.comments.count %></strong> <i class="fa fa-comments" style="color:green;" aria-hidden="true"></i>
                       </div>
                       <div class="col l4 m4 s4"></div>
                   </div>

                   <div class="card-action center"> <%= post.description%> </div>

               </div>
           </div>
      <% end %>
        <br>

</div>