config/routes.rb
Rails.application.routes.draw do

devise_for :admin_users, ActiveAdmin::Devise.config

get 'profile/:id'=> 'pages#profile' ,as: 'profile'
get 'followers/:id'=> 'pages#followers' ,as: 'followers'
get 'following/:id'=> 'pages#following' ,as: 'following'
resources :pages, only: [:index]

  root 'posts#index'

  resources :posts do
    resources :comments
    member do
    get 'like', to: "posts#like"
    get 'unlike', to: "posts#unlike"
  end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
resources :relationships,       only: [:create, :destroy]

    ActiveAdmin.routes(self)

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments ,dependent: :destroy
  acts_as_votable 

  has_attached_file :image, styles: {
     medium: "500x500>",
     large: "1000x1000>",
     thumb: "100x100>" },
     default_url: "https://s3.amazonaws.com/instatestbuck/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :description, presence: true, length:{minimum:3};
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!
before_action :post_owner, only: [:edit, :update, :destroy]

  def post_owner
    @post= Post.find( params[:id] )
   unless @post.user_id == current_user.id
    flash[:notice] = 'Access denied as you are not owner of this Post'
    redirect_to posts_path
   end
  end

  def index
    # @posts=Post.all.order('created_at DESC')

    following_ids = current_user.following.map(&:id)
    following_ids << current_user.id
    @posts=Post.where(user_id: following_ids).order("created_at DESC").paginate(page: params[:page])
  end

  def show
    @post= Post.find( params[:id] )
  end

  def destroy
    @post= Post.find( params[:id] )
    @post.destroy
      flash[:success]='Post deleted successfuly'
    redirect_to posts_path
  end

  def new
    @post=Post.new
  end

  def create
    @post=Post.new(permit_post)
    if @post.save
      flash[:success]='Post created successfuly'
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
      @post= Post.find( params[:id] )
  end

  def update
    @post= Post.find( params[:id] )
    if @post.update(params[:post].permit(:image,:description))
      flash[:success]='Post updated successfuly'
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def like
  @post = Post.find(params[:id])
  @post.liked_by current_user
  respond_to do |format|
    format.html { redirect_to :back }
    format.js { render layout: false }
  end
end

def unlike
  @post = Post.find(params[:id])
  @post.unliked_by current_user
  respond_to do |format|
    format.html { redirect_to :back }
    format.js { render layout: false }
  end
end

  private

    def permit_post
      params.require(:post).permit(:image,:description,:user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%if @post.errors.any?%>
  <div class="errors">
    <h2><%= pluralize(@post.errors.count,"error")%> prevented this post from saving</h2>
    <ul>
      <%= @post.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <%end%>

  <%=  f.hidden_field :user_id , value: current_user.id%>

  <%= f.label :photo%>
  <%= f.file_field :image %>
  <br>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <br>
  <%=f.submit%>
<%end%>

app/views/posts/index.html.erb
<%if @posts.any?%>
    <% @posts.each do |post|%>
    <br>
         <div class=" row single_post hoverable">
           <div class="col s12 card">
                <div class="card-action header row " style="padding:12px 10px 6px 10px; ">

                    <div class="col s1 l1 m1 left ">
                      <%= link_to profile_path(post.user) do%>
                        <div class="blue-text row valign-wrapper">
                          <div class="col s8 m8 l8"> <%= image_tag post.user.avatar.url(:thumb),class:"circle responsive-img"%></div>
                          <div class="col s1 m1 l1 valign-wrapper" style:" padding-right:20px;"> <%= post.user.username.capitalize %></div>
                        </div>
                      <%end%>
                    </div>

                    <div class="right col"> <%=time_ago_in_words(post.created_at)%> ago</div>

              </div>

                <br>
                <%= link_to post_path(post) do %>
                <div class="center">
                   <%= image_tag post.image.url(:medium), class:"responsive-img" %>
                 </div>
                 <%end%>
                <br>

                <hr>

                <div class="fame row" style="padding-top:1%;padding-bottom:2%; margin:0;">
                  <div class="col l5 m5 s4"></div>
                    <div class="col l1 m1 s2">
                      <strong><%= post.get_likes.size %></strong> <i class="fa fa-heart" style="color:#ff0000" aria-hidden="true"></i>
                    </div>
                    <div class="col l2 m2 s2">
                    <strong><%=post.comments.count %></strong> <i class="fa fa-comments" style="color:green;" aria-hidden="true"></i>
                    </div>
                    <div class="col l4 m4 s4"></div>
                </div>

                <div class="card-action center"> <%= post.description%> </div>
                <!-- <%= will_paginate %> -->
            </div>
        </div>
    <% end %>
<%end%>
<br><br>

app/views/posts/like.js.erb
$('.like_post').bind('ajax:success', function(){
  $(this).parent().parent().find('.vote_count').html('<div class="center"><h5><a class="dropdown-button" style="color:red;" data-hover="true" href="" data-activates="dropdown3"><%=escape_javascript pluralize(@post.votes_for.size.to_s,"Like") %></a></h5></div> <ul id="dropdown3" class="dropdown-content"> <% @post.get_likes.each do |like| %><li><%= link_to like.voter.username, profile_path(like.voter)%></li><% end %></ul>');
   $(this).closest('.like_post').hide();
   $(this).closest('.votes').html(' <%= link_to unlike_post_path(@post), style: "color:red;", remote: true, method: :get, class: 'unlike_post' do %> <div class="fa fa-heart fa-2x" style="color:#ff0000" aria-hidden="true"></div> <%end%> ');
});

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%if @post.errors.any?%>
  <div class="errors">
    <h2><%= pluralize(@post.errors.count,"error")%> prevented this post from saving</h2>
    <ul>
      <%= @post.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <%end%>

  <%=  f.hidden_field :user_id , value: current_user.id%>
  <%= f.label :photo%>
  <%= f.file_field :image %>
  <br>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <br>
  <%=f.submit%>
<%end%>

app/views/posts/show.html.erb
<br>
<div class="row single_post">

  <div class="card">
    <div class="card-action header row " style="padding:12px 10px 6px 10px; ">

        <div class="col s1 l1 m1 left ">
          <%= link_to profile_path(@post.user) do%>
            <div class="blue-text row valign-wrapper">
              <div class="col s8 m8 l8"> <%= image_tag @post.user.avatar.url(:thumb),class:"circle responsive-img"%></div>
              <div class="col s1 m1 l1 valign-wrapper" style:" padding-right:20px;"> <%= @post.user.username.capitalize %></div>
            </div>
          <%end%>
        </div>

      <%if (user_signed_in? && (current_user.id == @post.user_id))%>
           <div class="col right">

             <a class="dropdown-button red-text" data-constrainWidth="false" data-beloworigin="true" data-activates='post_options'><i class="fa fa-chevron-circle-down" aria-hidden="true"></i></a>

               <ul id='post_options' class='dropdown-content'>
                 <li ><%= link_to edit_post_path(@post) do %>
                    <i class="material-icons green-text"title="edit post" style="margin-right:2px">edit</i> edit
                   <%end%>
                 </li>
                 <li style="color:blue;"><%= link_to post_path(@post), method: :delete, data: {confirm:"Are you sure, do you want to 'DELETE' this post?"} do %>
                    <i class="material-icons red-text"title="delete post" style="margin-right:2px">delete</i> delete
                   <%end%>
                 </li>
               </ul>

          </div>
      <%end%>

      <div class="col right">
        <%= @post.created_at.strftime("%B,%d,%Y") %>
      </div>

    </div>

    <div align=center>
      <br>
       <%= image_tag @post.image.url(:medium), class:"responsive-img" %>
    </div>
    <br>
    <div class="card-action center">
     <%=@post.description%>
    </div>

<hr style="border: 0; border-top: 1px solid rgba(160, 160, 160, 0.2);">
    <div class="">

      <div class="vote_count">
        <div class="center"><h5><a class="dropdown-button" style="color:red;" href='' data-activates='dropdown1'><%= pluralize(@post.get_likes.size,"Like") %> </a></h5></div>
        <ul id='dropdown1' class='dropdown-content'>
        <% @post.get_likes.each do |like| %>
          <li><%= link_to like.voter.username, profile_path(like.voter)%></li>
        <% end %>
       </ul>
      </div>
<br>
      <div class="votes center">
        <% if current_user.liked? @post %>
          <%= link_to unlike_post_path(@post), style: "color:red;",  method: :get, remote: true, class: 'unlike_post' do%>
          <div class="fa fa-heart fa-2x" style="color:#ff0000" aria-hidden="true"> </div>
          <% end %>
        <% else %>
          <%= link_to like_post_path(@post), style: "color:red;",  method: :get, remote: true, class: 'like_post' do%>
          <div class="fa fa-heart-o fa-2x" aria-hidden="true"> </div>
          <%end%>
        <% end %>
      </div>

    </div>
<br>

    <div class="comments card-action s12">
       <div class="center"><h5 class="blue-text"><%= pluralize(@post.comments.count,"Comment") %> </h5></div>
      <br>
       <%= render @post.comments%>
       <%=render "comments/form"%>
    </div>

</div>

<br>
<br>
</div>

app/views/posts/unlike.js.erb
$('.unlike_post').bind('ajax:success', function(){
  $(this).parent().parent().find('.vote_count').html('<div class="center"><h5><a class="dropdown-button" style="color:red;" data-hover="true" href="" data-activates="dropdown2"><%= escape_javascript pluralize(@post.votes_for.size.to_s,"Like") %></a></h5></div> <ul id="dropdown2" class="dropdown-content"> <% @post.get_likes.each do |like| %><li><%= link_to like.voter.username, profile_path(like.voter)%></li><% end %></ul>');
   $(this).closest('.unlike_post').hide();
   $(this).closest('.votes').html(' <%= link_to like_post_path(@post), style: "color:red;",  remote: true, method: :get, class: 'like_post' do %> <div class="fa fa-heart-o fa-2x" aria-hidden="true"></div> <%end%>');

});
// $(this).parent().parent().find('.vote_count').html('<div class="center"><strong class="blue-text"><a class="dropdown-button" data-hover="true" href='#' data-activates='dropdown3'><%= escape_javascript pluralize(@post.votes_for.size.to_s,"Like") %></a></strong></div> <ul id='dropdown3' class='dropdown-content'> <% @post.get_likes.each do |like| %><li><%= link_to like.voter.username, profile_path(like.voter)%></li><% end %></ul>');